### PR TITLE
New blog post: Using torch.load from Julia

### PR DESCRIPTION
**Pull request by GregorySech**
Hi, I've written this very brief blog post about my first experience with the PyCall.jl package.
Let me know if it's enough or if you'd like something changed!

### CODE REVIEW

**Comment by Wikunia** [comment]
Hi Gregory,
that looks awesome thanks so much for the contribution.

**Comment by Wikunia** [comment]
Currently there seems to be still an error in my deploy script but your post will be live later :wink:

**Comment by GregorySech** [comment]
Thank you, no problem 😄  
On another note, I'm not sure if it was expected, but when I've run serve_twl I could see only the post I've created.
I've never used Franklin.jl so maybe it was configured to work like that.

**Comment by Wikunia** [comment]
Yeah I saw that as well and then rerun it and it worked. Still debugging that as well :smile:

**Comment by Wikunia** [comment]
Should be working fine now :smile:

**Comment by GregorySech** [comment]
Thank you! I hope to write some more in the coming weeks 😄

**Comment by Wikunia** [comment]
Great looking forward to it!

**Pull request merged**
